// Code generated by "stringer -type=sessionState,statusContextError -trimprefix=err -output enums_string.go"; DO NOT EDIT.

package getparty

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[sessionUncompleted-0]
	_ = x[sessionUncompletedWithAdvance-1]
	_ = x[sessionCompletedWithError-2]
	_ = x[sessionCompleted-3]
}

const _sessionState_name = "sessionUncompletedsessionUncompletedWithAdvancesessionCompletedWithErrorsessionCompleted"

var _sessionState_index = [...]uint8{0, 18, 47, 72, 88}

func (i sessionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_sessionState_index)-1 {
		return "sessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sessionState_name[_sessionState_index[idx]:_sessionState_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errContextPartial-0]
	_ = x[errContextFallback-1]
}

const _statusContextError_name = "ContextPartialContextFallback"

var _statusContextError_index = [...]uint8{0, 14, 29}

func (i statusContextError) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_statusContextError_index)-1 {
		return "statusContextError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statusContextError_name[_statusContextError_index[idx]:_statusContextError_index[idx+1]]
}
