// Code generated by "stringer -type=sessionMode -trimprefix=mode"; DO NOT EDIT.

package getparty

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[modePartial-0]
	_ = x[modeFallback-1]
}

const _sessionMode_name = "PartialFallback"

var _sessionMode_index = [...]uint8{0, 7, 15}

func (i sessionMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_sessionMode_index)-1 {
		return "sessionMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sessionMode_name[_sessionMode_index[idx]:_sessionMode_index[idx+1]]
}
